kind: pipeline
type: docker
name: default

platform:
  arch: arm64
  os: linux

steps:
- name: compile-and-upload-pages
  image: arm64v8/alpine
  environment:
    SSH_USER:
      from_secret: ssh_user
    SSH_ADDRESS:
      from_secret: ssh_address
    SSH_KEY:
      from_secret: ssh_key
  commands:
  - apk update && apk upgrade
  - apk add git openssh zola --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
  - git clone https://github.com/Vloupmon/blog.git
  - git -C blog submodule init && git -C blog submodule update
  - zola --root blog build --output-dir build
  - mkdir -p ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod og-rwx ~/.ssh/id_rsa
  - scp -o StrictHostKeyChecking=no -r '/build/*' $SSH_USER@$SSH_ADDRESS:/var/www/html/blog

trigger:
  branch:
  - master
